spring:
  datasource:
    username: root
    password: passwd1
    url: jdbc:mysql://localhost:3306/registration?useSSL=false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8086
  servlet:
    context-path: /mitrais
logging:
  level.root: info
  pattern:
      console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p})|%X{X-CORRELATION-ID}| %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

